#!/bin/bash
sudo apt update -y
sudo apt upgrade -y
sudo apt-get install -y --no-install-recommends xserver-xorg x11-xserver-utils xinit openbox
sudo apt install -y --no-install-recommends chromium-browser
sudo echo "xset -dpms" >> /etc/xdg/openbox/autostart
sudo echo "xset s noblank" >> /etc/xdg/openbox/autostart
sudo echo "xset s off" >> /etc/xdg/openbox/autostart
sudo echo "sed -i 's/\"exited_cleanly\":false/\"exited_cleanly\":true/' ~/.config/chromium/'Local State'" >> /etc/xdg/openbox/autostart
sudo echo "sed -i 's/\"exited_cleanly\":false/\"exited_cleanly\":true/; s/\"exit_type\":\"[^\"]\+\"/\"exit_type\":\"Normal\"/' ~/.config/chromium/Default/Preferences" >> /etc/xdg/openbox/autostart
sudo echo "chromium-browser  --noerrdialogs --disable-infobars --kiosk --check-for-update-interval=31536000 --disable-overscroll-edge-effect --disable-pinch \$KIOSK_URL" >> /etc/xdg/openbox/autostart
sudo echo "export KIOSK_URL=http://192.168.10.110" >> /etc/xdg/openbox/environment
sudo touch /home/pi/.bash_profile
sudo echo "[[ -z \$DISPLAY && \$XDG_VTNR -eq 1 ]] && startx -- -nocursor" >> /home/pi/.bash_profile
source /home/pi/.bash_profile
echo "Set autologin and overlayFs using the command 'sudo raspi-config', and then perform a reboot. Remember to take note of the IP address using the command 'ip address'!"
